baseurl = "http://kerikeri.top/"
title = "KERI's Lab"
languageCode = "ja-jp"
defaultContentLanguage = "ja"
paginate = "10" # Number of posts per page
disqusShortname = "kerikun11+disqus@gmail.com" # Enable comments by entering your Disqus shortname
googleAnalytics = "kerikun11" # Enable Google Analytics by entering your tracking id
hasCJKLanguage = true
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
rssLimit = 30 #default: 15
#rssuri = "feed.xml" # default: "index.xml"

[Author]
	name = "KERI"
	bio = "都内の大学に通う大学4年生．趣味は電子工作．最近はESP32に興味あり．マイクロマウスに挑戦中．"
	avatar = "/img/avatar.png"
	email = "kerikun11+web@gmail.com"
    location = "Earth"

[Params]
    subtitle = "KERI's Lab へようこそ。ここでは趣味の電子工作や日々の活動を紹介しています。" # Subtitle of your site
    description = "KERI's Lab へようこそ。ここでは趣味の電子工作や日々の活動を紹介しています。" # Description of your site
    opengraph = true
#    readmore = true # Show "Read more" button in list if true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = true
    post_navigation = true
#    postSections = ["post"] # the section pages to show on home page and the "Recent articles" widget
    dateformat = "2006-01-02" # change the format of dates
    pygmentscodefences = true
    pygmentsstyle = "default"

[taxonomies]
    tag = "tags"
    category = "categories"
    archive = "archives"
    spotlight = "spotlights"


[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent articles" widget
    recent_articles_num = 6 # Set the number of articles in the "Recent articles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
    tags_counter = true # Enable counter for each tag in "Tags" widget (disabled by default)
    social = true # Enable "Social" widget
#    social_facebook = "username"
    social_twitter = "Ryokeri14"
#    social_linkedin = ""
    social_github = "kerikun11"
    social_email = "kerikun11+web@gmail.com"

[permalinks]
    post = "/posts/:year-:month-:day-:slug/"
#    post = "/posts/:slug/"

[blackfriday]
#   plainIDAnchors = true
    hrefTargetBlank = true

