# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you ari expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site Settings
title: KERI's Lab
author: KERI
email: kerikun11+blog@gmail.com
description: KERI's Lab へようこそ。ここでは、趣味の電子工作やサーバーづくりなどを紹介しています。
baseurl: ""
url: "http://kerikeri.top"
twitter_username: Ryokeri14
github_username: kerikun11
permalink: /posts/:year-:month-:day-:title/

# Build Settings
markdown: kramdown
encording: UTF-8

# Plugin Settings

